AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template to create an IAM Role with permissions to manage AWS databases and related network configurations.'

Resources:
  DatabaseManagementRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      RoleName: 'DatabaseManagementRole'
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Principal: 
              Service: 
                - 'ec2.amazonaws.com'
                - 'lambda.amazonaws.com'
                - 'rds.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies: 
        - PolicyName: 'DatabaseManagementPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 'rds:*'
                  - 'dynamodb:*'
                  - 'neptune:*'
                  - 'docdb:*'
                  - 'redshift:*'
                  - 'ec2:Describe*'
                  - 'ec2:ModifyInstanceAttribute'
                  - 'ec2:CreateTags'
                  - 'ec2:DeleteTags'
                  - 'ec2:Associate*'
                  - 'ec2:Disassociate*'
                  - 'ec2:CreateVpc'
                  - 'ec2:ModifyVpc*'
                  - 'ec2:DeleteVpc'
                  - 'ec2:AuthorizeSecurityGroupIngress'
                  - 'ec2:RevokeSecurityGroupIngress'
                  - 'ec2:CreateSecurityGroup'
                  - 'ec2:DeleteSecurityGroup'
                  - 'ec2:DescribeSecurityGroups'
                  - 'ec2:ModifyNetworkInterfaceAttribute'
                  - 'kms:*'
                Resource: '*'
Outputs:
  RoleArn:
    Description: 'ARN of the IAM Role'
    Value: !GetAtt DatabaseManagementRole.Arn