AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an IAM role for Lambda creation and management.

Resources:
  LambdaCreationRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "LambdaCreationRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "LambdaCreationPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "lambda:CreateFunction"
                  - "lambda:UpdateFunctionCode"
                  - "lambda:UpdateFunctionConfiguration"
                  - "lambda:DeleteFunction"
                  - "lambda:GetFunction"
                  - "lambda:ListFunctions"
                  - "iam:PassRole"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

Outputs:
  LambdaCreationRoleArn:
    Description: "ARN of the IAM Role for creating Lambda functions"
    Value: !GetAtt LambdaCreationRole.Arn
