AWSTemplateFormatVersion: '2010-09-09'
Description: Add an inbound rule to an existing security group to allow access from a specific IP address

Parameters:
  SecurityGroupId:
    Type: String
    Description: The ID of the security group to update
  IpAddress:
    Type: String
    Description: The IP address to allow access
    AllowedPattern: ^(\d{1,3}\.){3}\d{1,3}(/(\d|[12]\d|3[0-2]))?$
    ConstraintDescription: Must be a valid IP address in CIDR notation

Resources:
  UpdateSecurityGroup:
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      GroupId: !Ref SecurityGroupId
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      CidrIp: !Ref IpAddress

Outputs:
  SecurityGroupId:
    Description: The ID of the updated security group
    Value: !Ref SecurityGroupId
